name: Deploy API to Fly
on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
jobs:
  deploy:
    name: Deploy API to Fly
    runs-on: ubuntu-latest
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      
    steps:
      - uses: actions/checkout@v3

      - name: Install flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy Spring Boot app to fly.io
        run: cd backend && flyctl deploy --remote-only